spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/food_delivery_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
jwt:
  secret-key: mySuperSecretJwtKeyForFoodDeliveryApplication2026WithExtraSymbols
  access-token-expiration: 30m
  refresh-token-expiration: 30d

logging:
  level:
    com.shh.foodeliverybackendapp.modules.otp: DEBUG