spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/food_delivery_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml